# Generated by Django 4.0.2 on 2022-02-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_summarytask_summary_summarytask_arrangement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarytask',
            name='professional',
        ),
    ]
