# Generated by Django 4.0.2 on 2022-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_summarytask_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytask',
            name='gold',
            field=models.TextField(null=True),
        ),
    ]
