# Generated by Django 4.0.2 on 2022-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_summarytask_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytask',
            name='subjectiveScore',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='summarytask',
            name='summaryID',
            field=models.IntegerField(null=True),
        ),
    ]
