# Generated by Django 4.0.2 on 2022-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_summarytask_subjectivescore_summarytask_summaryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytask',
            name='subjectiveScore',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
